repo: "navigation-highlight"
canvasCourse: "web-dev-1"

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 4
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - ['link[href*="Sigmar+One"]', 'The Google Font, `Sigmar One` is missing']
      - "header"
      - "header nav"
      - "header nav li"
      - "header nav li a"
      - "header h1"
      - "main"
      - "main h2"
      - "footer"
      - "footer small"
      - ['header nav li a[class][href*="index.html"]', 'The current page should be highlighted in the navigation']
    search:
      - "©"
      - "Berries, berries, oh my!"
      - "In everyday English"

  - path: "blueberries.html"
    valid: true
    bestPractices: true
    has:
      - ['header nav li a[class][href*="blueberries.html"]', 'The current page should be highlighted in the navigation']
      - 'img[src*="blueberries.jpg"]'
    search:
      - "Blueberries are perennial flowering plants"

  - path: "grapes.html"
    valid: true
    bestPractices: true
    has:
      - ['header nav li a[class][href*="grapes.html"]', 'The current page should be highlighted in the navigation']
      - 'img[src*="grapes.jpg"]'
    search:
      - "Grapes can be eaten raw"

  - path: "red-currants.html"
    valid: true
    bestPractices: true
    has:
      - ['header nav li a[class][href*="red-currants.html"]', 'The current page should be highlighted in the navigation']
      - 'img[src*="red-currants.jpg"]'
    search:
      - "the tart flavour of redcurrant"

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['*', 'box-sizing', 'inherit']
      - ['body', 'margin', '0']
      - ['img', 'display', 'block']
      - ['img', 'width', '100%']
    search:
      - "Georgia"
      - "Sigmar One"
      - "#2f2d13"
      - "#cc1465"
      - "#ffe500"
      - "#b20953"
      - "#b2a212"
      - "a:hover"

screenshots:
  - path: "index.html"
    sizes: [400]
  - path: "blueberries.html"
    sizes: [400]
  - path: "grapes.html"
    sizes: [400]
  - path: "red-currants.html"
    sizes: [400]

functionality:
  - path: 'index.html'
    tests:
      - |
        let link = $('nav li:last-child a');
        let oldBg = css(link).backgroundColor;

        hover('nav li:last-child a', function () {
          if (css(link).backgroundColor == oldBg) fail('The background colour of the link doesn’t change when hovered')
          pass();
        });
