repo: "navigation-highlight"
canvasCourse: "web-dev-1"

inherit:
  - naming-restrict-live
  - git-4
  - html
  - css
  - google-fonts
  - nav-hover
  - box-sizing
  - body-margin-0
  - img-block-100

html:
  - path: "index.html"
    has:
      - ['link[href*="Sigmar+One"]', 'The Google Font, `Sigmar One` is missing']
      - "header"
      - "header nav"
      - "header nav li"
      - "header nav li a"
      - "header h1"
      - "main"
      - "main h2"
      - "footer"
      - "footer small"
      - ['header nav li a[class][href*="index.html"]', 'The current page should be highlighted in the navigation']
    search:
      - "©"
      - "Berries, berries, oh my!"
      - "In everyday English"

  - path: "blueberries.html"
    has:
      - ['header nav li a[class][href*="blueberries.html"]', 'The current page should be highlighted in the navigation']
      - 'img[src*="blueberries.jpg"]'
    search:
      - "Blueberries are perennial flowering plants"

  - path: "grapes.html"
    has:
      - ['header nav li a[class][href*="grapes.html"]', 'The current page should be highlighted in the navigation']
      - 'img[src*="grapes.jpg"]'
    search:
      - "Grapes can be eaten raw"

  - path: "red-currants.html"
    has:
      - ['header nav li a[class][href*="red-currants.html"]', 'The current page should be highlighted in the navigation']
      - 'img[src*="red-currants.jpg"]'
    search:
      - "the tart flavour of redcurrant"

css:
  - path: "css/main.css"
    search:
      - "Georgia"
      - "Sigmar One"
      - "#2f2d13"
      - "#cc1465"
      - "#ffe500"
      - "#b20953"
      - "#b2a212"
      - "a:hover"

screenshots:
  - path: "index.html"
    sizes: [400]
  - path: "blueberries.html"
    sizes: [400]
  - path: "grapes.html"
    sizes: [400]
  - path: "red-currants.html"
    sizes: [400]
